linters:
  enable:
    - golint
    - govet
    - gofmt
    - structcheck
    - varcheck
    - interfacer
    - unconvert
    - ineffassign
    - goconst
    - gocyclo
    - maligned
    - misspell
    - nakedret
    - prealloc
    - gosec
    - deadcode
  disable-all: true
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  max-same-issues: 0
  max-per-linter: 0
  exclude:
    - "G108: Profiling endpoint is automatically exposed on /debug/pprof"
run:
  deadline: 4m
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*_mock.go$"
