apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gYWJjCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9IGFiYwpyZWdpb24gPSB1cy13ZXN0LTIKCg==
