apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
  annotations:
    ${MANAGEMENT_IAM_ARN/#arn/eks.amazonaws.com/role-arn: arn}
