name: CI

on:
  push:
    branches:
    - master

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: GCR Setup
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - name: GCR Auth
      uses: actions/gcloud/cli@master
      with:
        args: "auth configure-docker -q"

    - name: Build and push container images
      uses: actions/gcloud/cli@master
      with:
        entrypoint: /bin/bash
        args: |
          -c "apt-get -y update && \
              apt-get -y --no-install-recommends install build-essential && \
              make release-staging-latest"
